# Generated by Django 3.2.4 on 2021-06-14 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='firts_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='photographer',
            old_name='firts_name',
            new_name='first_name',
        ),
    ]
