# Generated by Django 3.2.4 on 2021-06-14 19:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_auto_20210614_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoshootSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.client')),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.photographer')),
            ],
        ),
    ]
